nodeSelector:
  workload: tools
  kubernetes.io/arch: arm64
tolerations:
  - key: workload
    value: tools
    effect: NoSchedule
webhook:
  nodeSelector:
    workload: tools
    kubernetes.io/arch: arm64
  tolerations:
    - key: workload
      value: tools
      effect: NoSchedule
certController:
  nodeSelector:
    workload: tools
    kubernetes.io/arch: arm64
  tolerations:
    - key: workload
      value: tools
      effect: NoSchedule