global:
  nodeSelector:
    workload: tools
    kubernetes.io/arch: arm64
  tolerations:
    - key: workload
      value: tools
      effect: NoSchedule 

# values-argocd.yaml (staging)
# configs:
#   cm:
#     application:
#       instanceLabelKey: argocd.argoproj.io/staging-instance 

configs:
  params:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/staging-instance

data:
  scopes: '[groups, email]'